language: python

python:
 - "3.4"

install:
- pip install coveralls
- pip install .

script:
 - coverage run -m unittest discover

notifications:
  email:
    recipients:
      - travis@michelblancard.fr
    on_success: change
    on_failure: always

after_success:
 - coveralls
